/* CafeGLSL source strings, mirrors shaders/q3uber_{vert,frag}.glsl verbatim.
 * Checked in by hand -- edit the .glsl files too if you change this. */

const char *shaderSrc_q3uber_vert =
"#version 450\n"
"\n"
"layout(location = 0) in vec3 in_Position;\n"
"layout(location = 1) in vec2 in_TexCoord0;\n"
"layout(location = 2) in vec2 in_TexCoord1;\n"
"layout(location = 3) in vec4 in_Color;\n"
"\n"
"layout(binding = 0) uniform VSBlock\n"
"{\n"
"	mat4 u_ModelViewProjection;\n"
"};\n"
"\n"
"layout(location = 0) out vec2 v_TexCoord0;\n"
"layout(location = 1) out vec2 v_TexCoord1;\n"
"layout(location = 2) out vec4 v_Color;\n"
"\n"
"void main()\n"
"{\n"
"	gl_Position = u_ModelViewProjection * vec4(in_Position, 1.0);\n"
"	v_TexCoord0 = in_TexCoord0;\n"
"	v_TexCoord1 = in_TexCoord1;\n"
"	v_Color = in_Color;\n"
"}\n";

const char *shaderSrc_q3uber_frag =
"#version 450\n"
"\n"
"layout(location = 0) in vec2 v_TexCoord0;\n"
"layout(location = 1) in vec2 v_TexCoord1;\n"
"layout(location = 2) in vec4 v_Color;\n"
"\n"
"layout(binding = 0) uniform PSBlock\n"
"{\n"
"	vec4 u_Mode;\n"
"	vec4 u_AlphaRef;\n"
"};\n"
"\n"
"layout(binding = 1) uniform GammaBlock\n"
"{\n"
"	vec4 u_InvGamma;\n"
"};\n"
"\n"
"layout(binding = 0) uniform sampler2D s_Base;\n"
"layout(binding = 1) uniform sampler2D s_Lightmap;\n"
"\n"
"layout(location = 0) out vec4 out_Color;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 color = v_Color;\n"
"\n"
"	if (u_Mode.x > 0.5) {\n"
"		color *= texture(s_Base, v_TexCoord0);\n"
"	}\n"
"\n"
"	if (u_Mode.y > 0.5) {\n"
"		vec4 lm = texture(s_Lightmap, v_TexCoord1);\n"
"		if (u_Mode.z > 0.5) {\n"
"			color += lm;\n"
"		} else {\n"
"			color *= lm;\n"
"		}\n"
"	}\n"
"\n"
"	if (u_Mode.w > 0.5 && u_Mode.w < 1.5) {\n"
"		if (color.a <= 0.0) discard;\n"
"	} else if (u_Mode.w > 1.5 && u_Mode.w < 2.5) {\n"
"		if (color.a >= 0.5) discard;\n"
"	} else if (u_Mode.w > 2.5) {\n"
"		if (color.a < u_AlphaRef.x) discard;\n"
"	}\n"
"\n"
"	color.rgb = pow(color.rgb, vec3(u_InvGamma.x));\n"
"\n"
"	out_Color = color;\n"
"}\n";
